In [41]:
import numpy as np
np.random.seed(8)

In [111]:
import numpy as np
np.random.seed(8)


def gen_new_field(x, y, mines):
    true_field = np.full(x*y, 0)
    m = 0
    while mines > m:
        i = np.random.randint(0, x*y)
        if true_field[i] != -1:
            true_field[i] = -1
            m += 1
    true_field.shape = (x, y)
    visible_field = np.full((x, y), "▓")
    return true_field, visible_field


a, b = gen_new_field(5, 5, 5)
print(a)
# print(b)



[[ 0  0  0 -1  0]
 [-1  0  0  0 -1]
 [ 0  0  0  0  0]
 [ 0  0 -1  0  0]
 [-1  0  0  0  0]]


In [ ]:
    for i in true_field:
        for j in true_field:
            s = (i-1 if i>1 else 0: i+1 if i<x-1 else x-1, j-1 if j>1 else 0: j+1 if j<y-1 else y-1)

In [113]:
i = 4
j = 1
s = a[i-1 if i>0 else 0: i+2 if i<x-1 else x-1, j-1 if j>1 else 0: j+2 if j<y-1 else y-1]
print(s)

[[ 0  0 -1]]


i-1 if i>1 else 0              :               i+2 if i<x-1 else x-1

In [127]:
i = 1
j = 4
q = a[i-1 if i>1 else 0: i+2, j-1 if j>0 else 0: j+2]
print(q)

[[-1  0]
 [ 0 -1]
 [ 0  0]]


In [128]:
print(a[3,2])

-1
